# Generated by Django 3.2.4 on 2022-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220401_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, upload_to='posts', verbose_name='Изображение'),
        ),
    ]
